n1,n2=15,7
addition=n1+n2
subtraction=n1-n2
multiplication=n1*n2
division=n1/n2
IntegerDivision=n1//n2
remainder=n1%n2
exponential=n1**n2
print(addition)
print(subtraction)
print(multiplication)
print(division)
print(IntegerDivision)
print(remainder)
print(exponential)
